### PR TITLE
Remove the trailing slash

### PR DESCRIPTION
**Pull request by IonicaBizau**
We can simply `require(".")` to require the current directory. :grin:

### CODE REVIEW

**Comment by zeke** [comment]
No way! Wish I knew that a long time ago.

It will take me a lifetime to remove all those unneeded slashes from all my projects. :)

**Comment by zeke** [comment]
Thanks @IonicaBizau. This change will roll out the next time [the release script runs itself](http://zeke.sikelianos.com/npm-and-github-automation-with-heroku/).

**Comment by IonicaBizau** [comment]
@zeke Just create a script to replace and update that across the repos. 😄 It's probably something like `:%s/\(('|")\.\./('|")\)/\('\.\.'\)` and `:%s/\(('|")\./('|")\)/\('\.'\)`.

Actually, if you like, I can do it for you. 😜

**Comment by zeke** [comment]
> Actually, if you like, I can do it for you. 😜

Be my guest!

**Comment by IonicaBizau** [comment]
@zeke Done. 🚀 🎉 

Probably I spammed you with few emails, but for convenience, check this out: https://github.com/pulls?utf8=✓&q=is%3Aopen+is%3Apr+author%3AIonicaBizau+user%3Azeke

Some of the tests are failing, but most probably because `.travis.yml` is missing.

This is the magic command:

> `sed -i -e "s/require(\"\.\/\")/require\(\'\.\'\)/g" *.js && rm *.js-e && git commit -m 'Removed trailing slash' . && git push --all`

**Comment by zeke** [comment]
@IonicaBizau you are a wizard. Thanks so much! I had forgotten about half those projects. 🙈

**Comment by IonicaBizau** [comment]
@zeke Cool! You're welcome. 😁 I update mine each few months, automagically (especially keeping the README.md files to follow the same template). 🚀

**Pull request merged**
